apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2-server
  template:
    metadata:
      labels:
        app: h2-server
    spec:
      containers:
        - name: h2
          image: oscarfonts/h2:latest
          ports:
            - containerPort: 1521
            - containerPort: 81
          env:
            - name: H2_OPTIONS
              value: -ifNotExists
          volumeMounts:
            - name: h2-data
              mountPath: /opt/h2-data
      volumes:
        - name: h2-data
          persistentVolumeClaim:
            claimName: h2-data-pvc