apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-productos-backend
  template:
    metadata:
      labels:
        app: ms-productos-backend
    spec:
      containers:
        - name: ms-productos-backend-container
          image: anthonyponte/ms-productos-backend:1.0.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 9095
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:tcp://h2-server:1521/productos;IFEXISTS=FALSE
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: del1al9