apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-productos
  template:
    metadata:
      labels:
        app: ms-productos
    spec:
      containers:
        - name: ms-productos-container
          image: anthonyponte/ms-productos:v2
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 9095
          volumeMounts:
            - name: h2-storage
              mountPath: /h2-data
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:file:/h2-data/msdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: del1al9
      volumes:
        - name: h2-storage
          persistentVolumeClaim:
            claimName: h2-pvc