apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msproductos-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "msproductos.anthonyponte.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: msproductos-service
            port:
              number: 9095